export const ADD_ITEMS = 'ADD_ITEMS'
export const ADD_ITEMS_SUCCESSFUL = 'ADD_ITEMS_SUCCESSFUL'
export const ADD_ITEMS_WRONG = 'ADD_ITEMS_WRONG'
export const SET_CURRENT_VALUES = 'SET_CURRENT_VALUES';

export const ADD_DETAIL_ITEM = 'ADD_DETAIL_ITEM'
export const ADD_DETAIL_ITEM_SUCCESSFUL = 'ADD_DETAIL_ITEM_SUCCESSFUL'
export const ADD_DETAIL_ITEM_WRONG = 'ADD_DETAIL_ITEM_WRONG'